/**
 * Shared color/shape normalization helpers and the built-in procedural
 * texture style tables used by the bricks Pixi renderer.
 */
import * as PIXI from 'pixi.js';

// Helper to convert CSS color strings or numeric values into Pixi-compatible numbers
export const toPixiColor = (value: unknown) => {
  if (value === null || value === undefined || value === '') {
    return 0xffffff;
  }
  const normalized = typeof value === 'string' ? value.trim() : value;
  try {
    return PIXI.Color.shared.setValue(normalized as PIXI.ColorSource).toNumber();
  } catch (error) {
    console.warn(`[bricks] Failed to convert color: ${value}`, error);
    return 0xffffff;
  }
};
export const normalizeBrickShape = (rawShape: unknown): string => {
  if (typeof rawShape !== 'string') {
    return 'rounded_rect';
  }
  const normalized = rawShape.trim().toLowerCase();
  if (!normalized) {
    return 'rounded_rect';
  }
  const aliases = {
    square: 'rect',
    rectangle: 'rect',
    rounded: 'rounded_rect',
    rounded_rectangle: 'rounded_rect'
  };
  return (aliases as Record<string, string>)[normalized] ?? normalized;
};

export const normalizeTextureStyleId = (value: unknown): string => {
  if (typeof value !== 'string') {
    return '';
  }
  return value.trim().toLowerCase().replace(/[\s-]+/g, '_');
};

export const BUILTIN_BRICK_TEXTURE_STYLES = {
  crate: {
    pattern: 'wood_planks',
    baseFillColor: '#8b6f4e',
    baseFillAlpha: 1,
    alpha: 0.95,
    plankCount: 3,
    grainCount: 5,
    seamColor: '#3b2f22',
    highlightColor: '#f5e9d8',
  },
  present: {
    pattern: 'gift_wrap',
    baseFillColor: '#ff2d2d',
    baseFillAlpha: 1,
    alpha: 1,
    ribbonColor: '#ffe14d',
    ribbonAlpha: 1,
    ribbonWidthRatio: 0.2,
    ribbonInsetPx: 2,
    topSheenAlpha: 0.08,
    paperPatternColor: '#ffffff',
    paperPatternAlpha: 0.38,
  },
  pizza: {
    pattern: 'pizza',
    baseFillColor: '#e2b07b',
    baseFillAlpha: 1,
    alpha: 1,
    sliceCount: 6,
    toppingCount: 7,
    crustColor: '#a16207',
    sauceColor: '#b91c1c',
    cheeseColor: '#facc15',
    toppingColor: '#7f1d1d',
    sliceLineColor: '#7c2d12',
  },
  box: {
    pattern: 'checkerboard',
    baseFillColor: '#b4936b',
    checkerColorA: '#9a7651',
    checkerColorB: '#5f6976',
    checkerCellPx: 2,
    baseFillAlpha: 1,
    alpha: 0.9,
    insetPx: 2,
    topSheenAlpha: 0,
    highlightColor: '#f1e5d5',
  },
  checkerboard: {
    pattern: 'checkerboard',
    baseFillColor: '#7d8794',
    checkerColorA: '#a9b4c2',
    checkerColorB: '#7e5f40',
    checkerCellPx: 12,
    baseFillAlpha: 1,
    alpha: 0.9,
    insetPx: 2,
    topSheenAlpha: 0,
    highlightColor: '#f8fafc',
  },
  parcel_label: {
    pattern: 'cardboard_block',
    baseFillColor: '#b4936b',
    baseFillAlpha: 1,
    alpha: 0.96,
    insetPx: 2,
    topSheenAlpha: 0,
    highlightColor: '#f1e5d5',
    fiberColor: '#9a7651',
    fiberAlpha: 0,
    fiberStepPx: 6,
    speckleColor: '#7e5f40',
    speckleAlpha: 0,
    speckleCount: 0,
    labelPatch: true,
    labelPatchColor: '#fbfdff',
    labelPatchAlpha: 0.86,
    labelPatchBorderColor: '#475569',
    labelBarcodeColor: '#111827',
  },
  chest: {
    pattern: 'wood_planks',
    baseFillColor: '#6d4b31',
    baseFillAlpha: 1,
    alpha: 0.98,
    plankCount: 3,
    seamWidthPx: 1,
    grainCount: 5,
    nailRadiusPx: 1.25,
    insetPx: 2,
    topSheenAlpha: 0.22,
    seamColor: '#2b1e14',
    highlightColor: '#f5d8a6',
    bandColor: '#f1f5f9',
    bandAlpha: 0.3,
    lockPlateColor: '#fef3c7',
    lockPlateAlpha: 0.7,
  },
};

export const BUILTIN_END_FURNACE_STYLES = {
  furnace: {},
  crusher: {
    wallColor: '#6b7280',
    wallShadeColor: '#434a55',
    rimColor: '#f3f4f6',
    mouthColor: '#111827',
    emberColor: '#ef4444',
    bodyPanelLines: true,
    hazardStripes: true,
    sideRivets: true,
  },
  shredder: {
    wallColor: '#475569',
    wallShadeColor: '#334155',
    rimColor: '#cbd5e1',
    mouthColor: '#020617',
    emberColor: '#60a5fa',
    bodyPanelLines: true,
    hazardStripes: false,
    sideRivets: true,
  },
  plasma_recycler: {
    wallColor: '#0f172a',
    wallShadeColor: '#1e293b',
    rimColor: '#94a3b8',
    mouthColor: '#020617',
    emberColor: '#a78bfa',
    bodyPanelLines: false,
    hazardStripes: false,
    sideRivets: true,
  },
};

export const BUILTIN_WAREHOUSE_TEXTURE_STYLES = {
  concrete_checker: {
    tileSizePx: 240,
    paverWidthPx: 82,
    paverHeightPx: 82,
    groutPx: 3,
    layout: 'grid',
    rowOffsetPx: 0,
    pattern: 'checker_alternating',
    alternationStrength: 0.07,
    variation: 0.12,
    edgeShadingAlpha: 0,
    noiseCount: 20,
    seamDashCount: 8,
    baseColor: '#8f959c',
    groutColor: '#6e757e',
    seamDarkColor: '#4b545f',
    seamLightColor: '#b4bac1',
    scratchColor: '#5a616b',
  },
  cold_blueprint: {
    tileSizePx: 228,
    paverWidthPx: 76,
    paverHeightPx: 76,
    groutPx: 2,
    layout: 'grid',
    pattern: 'checker_alternating',
    alternationStrength: 0.06,
    variation: 0.08,
    edgeShadingAlpha: 0,
    noiseCount: 18,
    seamDashCount: 8,
    baseColor: '#96acbf',
    groutColor: '#72889b',
    seamDarkColor: '#526678',
    seamLightColor: '#c9d7e3',
    scratchColor: '#5f7387',
  },
  lab_metal_rivet: {
    tileSizePx: 220,
    paverWidthPx: 72,
    paverHeightPx: 72,
    groutPx: 2,
    layout: 'grid',
    pattern: 'checker_alternating',
    alternationStrength: 0.05,
    variation: 0.07,
    edgeShadingAlpha: 0.06,
    noiseCount: 14,
    seamDashCount: 8,
    rivetCount: 36,
    dentCount: 6,
    baseColor: '#8ea0ad',
    groutColor: '#617380',
    seamDarkColor: '#465560',
    seamLightColor: '#c6d3de',
    scratchColor: '#51606b',
    rivetColor: '#dbe8f2',
  },
  wood_corrugation: {
    tileSizePx: 246,
    paverWidthPx: 92,
    paverHeightPx: 76,
    groutPx: 2,
    layout: 'staggered',
    rowOffsetPx: 46,
    pattern: 'none',
    variation: 0.12,
    edgeShadingAlpha: 0.15,
    noiseCount: 20,
    seamDashCount: 12,
    baseColor: '#9a8266',
    groutColor: '#715c47',
    seamDarkColor: '#5a4736',
    seamLightColor: '#c3ae92',
    scratchColor: '#5b4939',
  },
  damaged_salvage: {
    tileSizePx: 232,
    paverWidthPx: 84,
    paverHeightPx: 84,
    groutPx: 2,
    layout: 'grid',
    pattern: 'checker_alternating',
    alternationStrength: 0.08,
    variation: 0.11,
    edgeShadingAlpha: 0.08,
    noiseCount: 22,
    seamDashCount: 14,
    rivetCount: 18,
    dentCount: 12,
    crackCount: 14,
    baseColor: '#7a838e',
    groutColor: '#545c66',
    seamDarkColor: '#3d434c',
    seamLightColor: '#9ea7b2',
    scratchColor: '#474e57',
    rivetColor: '#cbd5e1',
  },
  salvage_rivet: {
    tileSizePx: 224,
    paverWidthPx: 74,
    paverHeightPx: 74,
    groutPx: 2,
    layout: 'grid',
    pattern: 'checker_alternating',
    alternationStrength: 0.06,
    variation: 0.08,
    edgeShadingAlpha: 0.06,
    noiseCount: 16,
    seamDashCount: 10,
    rivetCount: 28,
    dentCount: 8,
    baseColor: '#7f8b97',
    groutColor: '#596572',
    seamDarkColor: '#414b55',
    seamLightColor: '#bac7d4',
    scratchColor: '#49545f',
    rivetColor: '#d8e3ee',
  },
};

export const BUILTIN_BELT_TEXTURE_STYLES = {
  industrial_ribbed: {
    tileSizePx: 120,
    ribStepPx: 12,
    ribWidthPx: 8,
    sideBandPx: 18,
    sideCleatStepPx: 16,
    sideCleatLengthPx: 12,
    shadeAlpha: 0.55,
    baseColor: '#2a323b',
    shadeColor: '#202730',
    ribColor: '#4d5863',
    grooveColor: '#2b333c',
    sideCleatColor: '#6b7280',
    sideLineDarkColor: '#111827',
    sideLineLightColor: '#9ca3af',
  },
  cold_blueprint_belt: {
    tileSizePx: 126,
    ribStepPx: 13,
    ribWidthPx: 8,
    sideBandPx: 18,
    sideCleatStepPx: 16,
    sideCleatLengthPx: 11,
    shadeAlpha: 0.5,
    baseColor: '#3a5166',
    shadeColor: '#23384a',
    ribColor: '#69859e',
    grooveColor: '#2b3f51',
    sideCleatColor: '#8aa4bc',
    sideLineDarkColor: '#0f172a',
    sideLineLightColor: '#dbeafe',
  },
  lab_ribbed: {
    tileSizePx: 122,
    ribStepPx: 12,
    ribWidthPx: 8,
    sideBandPx: 18,
    sideCleatStepPx: 16,
    sideCleatLengthPx: 12,
    shadeAlpha: 0.56,
    baseColor: '#3a4c5c',
    shadeColor: '#223544',
    ribColor: '#617b90',
    grooveColor: '#2a3b49',
    sideCleatColor: '#8ca1b4',
    sideLineDarkColor: '#0f172a',
    sideLineLightColor: '#dbeafe',
    scuffCount: 8,
  },
  wood_corrugation_belt: {
    tileSizePx: 116,
    ribStepPx: 10,
    ribWidthPx: 7,
    sideBandPx: 16,
    sideCleatStepPx: 14,
    sideCleatLengthPx: 10,
    shadeAlpha: 0.58,
    baseColor: '#4a3929',
    shadeColor: '#2e2419',
    ribColor: '#70583f',
    grooveColor: '#3b2d21',
    sideCleatColor: '#8a7359',
    sideLineDarkColor: '#1a130d',
    sideLineLightColor: '#d1bfa7',
  },
  damaged_patched_belt: {
    tileSizePx: 118,
    ribStepPx: 11,
    ribWidthPx: 7,
    sideBandPx: 17,
    sideCleatStepPx: 15,
    sideCleatLengthPx: 10,
    shadeAlpha: 0.62,
    baseColor: '#38414a',
    shadeColor: '#212a33',
    ribColor: '#55606b',
    grooveColor: '#2a323b',
    sideCleatColor: '#68727d',
    sideLineDarkColor: '#0b1120',
    sideLineLightColor: '#b7c2ce',
    scuffCount: 18,
    patchCount: 8,
  },
  salvage_shredder_belt: {
    tileSizePx: 114,
    ribStepPx: 11,
    ribWidthPx: 7,
    sideBandPx: 17,
    sideCleatStepPx: 15,
    sideCleatLengthPx: 10,
    shadeAlpha: 0.6,
    baseColor: '#343d46',
    shadeColor: '#1f2730',
    ribColor: '#515d69',
    grooveColor: '#2a333c',
    sideCleatColor: '#738190',
    sideLineDarkColor: '#060b14',
    sideLineLightColor: '#d6e0ea',
    scuffCount: 10,
  },
};
